using System.Text;
using System.Xml.Linq;
using LordHelm.Core;
using Microsoft.Extensions.Logging;

namespace LordHelm.Skills.Export;

/// <summary>
/// Pushes LordHelm manifests into Codex's <c>~/.codex/prompts/</c> directory
/// as plain markdown files. Codex surfaces them via the <c>/prompt &lt;name&gt;</c>
/// slash command inside its REPL.
///
/// The Codex prompt format is simpler than Claude's SKILL.md — no YAML
/// frontmatter, no parameter-schema validation; the file body is treated as
/// instruction text Codex injects into the session when invoked. We keep the
/// markdown structure (description, parameters, risk) for operator
/// readability and as hints the model will actually read.
/// </summary>
public sealed class CodexPromptExporter : ISkillExporter
{
    private readonly ILogger<CodexPromptExporter> _logger;
    private readonly string? _promptsDir;

    public string VendorId => "codex";
    public string? TargetDirectory => _promptsDir;

    public CodexPromptExporter(ILogger<CodexPromptExporter> logger, string? overrideDir = null)
    {
        _logger = logger;
        var home = overrideDir ?? Environment.GetEnvironmentVariable("USERPROFILE")
            ?? Environment.GetEnvironmentVariable("HOME");
        _promptsDir = home is null ? null : Path.Combine(home, ".codex", "prompts");
    }

    public bool IsSupported() => !string.IsNullOrEmpty(_promptsDir);

    public async Task<ExportReport> ExportAsync(
        IReadOnlyList<SkillManifest> manifests, bool overwrite, CancellationToken ct = default)
    {
        if (_promptsDir is null)
            return new ExportReport(VendorId, 0, 0, 0,
                new[] { "HOME/USERPROFILE env not set; can't resolve Codex prompts dir" }, null);

        Directory.CreateDirectory(_promptsDir);
        var errors = new List<string>();
        int written = 0, skipped = 0;

        // Codex's convention is AGENTS.md at the project root or config
        // dir. Write the orchestration briefing there so it's loaded as
        // session context when the operator starts a codex session.
        try
        {
            var configDir = Directory.GetParent(_promptsDir)!.FullName;
            var briefingPath = Path.Combine(configDir, "AGENTS.md");
            if (overwrite || !File.Exists(briefingPath))
            {
                await File.WriteAllTextAsync(briefingPath,
                    VendorBriefing.ForVendor("codex", manifests.Count, _promptsDir),
                    Encoding.UTF8, ct);
            }
        }
        catch (Exception ex) { errors.Add($"briefing: {ex.Message}"); }

        foreach (var m in manifests)
        {
            if (ct.IsCancellationRequested) break;
            try
            {
                var file = Path.Combine(_promptsDir, SafeFileName(m.Id) + ".md");
                if (File.Exists(file) && !overwrite) { skipped++; continue; }
                await File.WriteAllTextAsync(file, BuildPromptMd(m), Encoding.UTF8, ct);
                written++;
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "codex export failed for {Id}", m.Id);
                errors.Add($"{m.Id}: {ex.Message}");
            }
        }
        _logger.LogInformation(
            "Codex prompt export: {Written} written, {Skipped} skipped, {Errors} errors",
            written, skipped, errors.Count);
        return new ExportReport(VendorId, manifests.Count, written, skipped, errors, _promptsDir);
    }

    public static string BuildPromptMd(SkillManifest m)
    {
        var (description, tags) = ExtractFromXml(m.CanonicalXml);
        var sb = new StringBuilder();
        sb.Append("# ").AppendLine(Titleize(m.Id));
        sb.AppendLine();
        sb.AppendLine(description);
        sb.AppendLine();
        if (tags.Count > 0) sb.Append("_Tags: ").Append(string.Join(", ", tags)).AppendLine("_").AppendLine();
        sb.AppendLine("## Parameters");
        sb.AppendLine("```json");
        sb.AppendLine(m.ParameterSchemaJson.Trim());
        sb.AppendLine("```");
        sb.AppendLine();
        sb.Append("> Execution context: `").Append(m.ExecEnv).Append("` · risk `")
          .Append(m.RiskTier).Append("`").Append(m.RequiresApproval ? " · requires approval" : "").AppendLine();
        sb.AppendLine();
        sb.Append("_Generated by Lord Helm from manifest `").Append(m.Id).Append("` v").Append(m.Version).AppendLine("._");
        return sb.ToString();
    }

    internal static (string Description, IReadOnlyList<string> Tags) ExtractFromXml(string canonicalXml)
    {
        try
        {
            var doc = XDocument.Parse(canonicalXml);
            var ns = doc.Root?.GetDefaultNamespace() ?? XNamespace.None;
            var desc = doc.Root?.Element(ns + "Description")?.Value?.Trim() ?? "";
            var tags = doc.Root?.Element(ns + "Tags")?.Elements(ns + "Tag")
                .Select(t => t.Value?.Trim() ?? "")
                .Where(t => t.Length > 0)
                .ToList() ?? new List<string>();
            return (desc, tags);
        }
        catch { return ("", Array.Empty<string>()); }
    }

    private static string SafeFileName(string id) =>
        new string(id.Select(c => char.IsLetterOrDigit(c) || c == '-' || c == '_' ? c : '-').ToArray());

    private static string Titleize(string id)
    {
        var parts = id.Split('-', '_');
        return string.Join(' ', parts.Select(p =>
            p.Length == 0 ? p : char.ToUpperInvariant(p[0]) + p.Substring(1)));
    }
}
