using System.Text;
using System.Xml.Linq;
using LordHelm.Core;
using Microsoft.Extensions.Logging;

namespace LordHelm.Skills.Export;

/// <summary>
/// Pushes LordHelm manifests into Gemini CLI's <c>~/.gemini/commands/</c>
/// directory as markdown files. Gemini's custom-command surface is still
/// evolving; we write one markdown per manifest with a minimal header so
/// operators can then reference them as context or invoke via slash
/// commands depending on the CLI version.
/// </summary>
public sealed class GeminiCommandExporter : ISkillExporter
{
    private readonly ILogger<GeminiCommandExporter> _logger;
    private readonly string? _commandsDir;

    public string VendorId => "gemini";
    public string? TargetDirectory => _commandsDir;

    public GeminiCommandExporter(ILogger<GeminiCommandExporter> logger, string? overrideDir = null)
    {
        _logger = logger;
        var home = overrideDir ?? Environment.GetEnvironmentVariable("USERPROFILE")
            ?? Environment.GetEnvironmentVariable("HOME");
        _commandsDir = home is null ? null : Path.Combine(home, ".gemini", "commands");
    }

    public bool IsSupported() => !string.IsNullOrEmpty(_commandsDir);

    public async Task<ExportReport> ExportAsync(
        IReadOnlyList<SkillManifest> manifests, bool overwrite, CancellationToken ct = default)
    {
        if (_commandsDir is null)
            return new ExportReport(VendorId, 0, 0, 0,
                new[] { "HOME/USERPROFILE env not set; can't resolve Gemini commands dir" }, null);

        Directory.CreateDirectory(_commandsDir);
        var errors = new List<string>();
        int written = 0, skipped = 0;

        // Gemini CLI's convention is GEMINI.md at the config-dir root.
        // Write the orchestration briefing there so it loads as session
        // context on next `gemini` invocation.
        try
        {
            var configDir = Directory.GetParent(_commandsDir)!.FullName;
            var briefingPath = Path.Combine(configDir, "GEMINI.md");
            if (overwrite || !File.Exists(briefingPath))
            {
                await File.WriteAllTextAsync(briefingPath,
                    VendorBriefing.ForVendor("gemini", manifests.Count, _commandsDir),
                    Encoding.UTF8, ct);
            }
        }
        catch (Exception ex) { errors.Add($"briefing: {ex.Message}"); }

        foreach (var m in manifests)
        {
            if (ct.IsCancellationRequested) break;
            try
            {
                var file = Path.Combine(_commandsDir, SafeFileName(m.Id) + ".md");
                if (File.Exists(file) && !overwrite) { skipped++; continue; }
                await File.WriteAllTextAsync(file, BuildCommandMd(m), Encoding.UTF8, ct);
                written++;
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "gemini export failed for {Id}", m.Id);
                errors.Add($"{m.Id}: {ex.Message}");
            }
        }
        _logger.LogInformation(
            "Gemini command export: {Written} written, {Skipped} skipped, {Errors} errors",
            written, skipped, errors.Count);
        return new ExportReport(VendorId, manifests.Count, written, skipped, errors, _commandsDir);
    }

    public static string BuildCommandMd(SkillManifest m)
    {
        var (description, tags) = ExtractFromXml(m.CanonicalXml);
        var sb = new StringBuilder();
        sb.AppendLine("---");
        sb.Append("name: ").AppendLine(m.Id);
        sb.Append("description: ").AppendLine(description);
        sb.AppendLine("---");
        sb.AppendLine();
        sb.Append("# ").AppendLine(Titleize(m.Id));
        sb.AppendLine();
        sb.AppendLine(description);
        sb.AppendLine();
        if (tags.Count > 0) sb.Append("**Tags:** ").AppendLine(string.Join(", ", tags)).AppendLine();
        sb.AppendLine("## Parameters");
        sb.AppendLine("```json");
        sb.AppendLine(m.ParameterSchemaJson.Trim());
        sb.AppendLine("```");
        sb.AppendLine();
        sb.Append("Env `").Append(m.ExecEnv).Append("` · risk `").Append(m.RiskTier).Append("`")
          .Append(m.RequiresApproval ? " · requires approval" : "").AppendLine();
        sb.AppendLine();
        sb.Append("_Generated by Lord Helm from manifest `").Append(m.Id).Append("` v").Append(m.Version).AppendLine("._");
        return sb.ToString();
    }

    internal static (string Description, IReadOnlyList<string> Tags) ExtractFromXml(string canonicalXml)
    {
        try
        {
            var doc = XDocument.Parse(canonicalXml);
            var ns = doc.Root?.GetDefaultNamespace() ?? XNamespace.None;
            var desc = doc.Root?.Element(ns + "Description")?.Value?.Trim() ?? "";
            var tags = doc.Root?.Element(ns + "Tags")?.Elements(ns + "Tag")
                .Select(t => t.Value?.Trim() ?? "")
                .Where(t => t.Length > 0)
                .ToList() ?? new List<string>();
            return (desc, tags);
        }
        catch { return ("", Array.Empty<string>()); }
    }

    private static string SafeFileName(string id) =>
        new string(id.Select(c => char.IsLetterOrDigit(c) || c == '-' || c == '_' ? c : '-').ToArray());

    private static string Titleize(string id)
    {
        var parts = id.Split('-', '_');
        return string.Join(' ', parts.Select(p =>
            p.Length == 0 ? p : char.ToUpperInvariant(p[0]) + p.Substring(1)));
    }
}
